trigger: none

parameters:
- name: clientId
  displayName: Client name
  type: string

- name: dccAccount
  displayName: dcc account
  type: string

jobs:
- job: Work
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        if [ "${{ parameters.dccAccount }}" == "True"]; then
          MANAGEMENT_GROUP_NAME = "DT_CCMS_SERVICES"
          echo $MANAGEMENT_GROUP_NAME
        else
          echo $MANAGEMENT_GROUP_NAME
        fi
      
    displayName: 'Run a one-line script'

