
trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world'
- job: WaitForValidation
  pool: server
  displayName: Wait for approval
  timeoutInMinutes: 30
  steps:
    - task: ManualValidation@0
      timeoutInMinutes: 30 # task times out in 30 minutes
      inputs:
        notifyUsers: |
          zaki.spofy@gmail.com
          zakaria.itispin@gmail.com
          zack.fatouh@outlook.fr
        instructions: 'Approve the Terraform Apply'

